
name: GitHub Actions For Instagram CLone
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Instaclone
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        env:
            REACT_APP_FIREBASE_API_KEY: ${{secrets.FIREBASE_SECERT}}
            REACT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_SECERT}}
            REACT_APP_FIREBASE_DATABASE_URL:  ${{secrets.FIREBASE_SECERT}}
            REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_SECERT}}
            REACT_APP_FIREBASE_STORAGE_BUCKET:  ${{secrets.FIREBASE_SECERT}}
            REACT_APP_FIREBASE_MESSAGING_SENDER_ID:  ${{secrets.FIREBASE_SECERT}}
            REACT_APP_FIREBASE_APP_ID: ${{secrets.FIREBASE_SECERT}}
            repository: ${{ github.repository }}